name: bookingnow_app
description: "BookingNow - Reservas de citas para cualquier servicio. App para clientes y negocios + panel web de administracion."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.8.0
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  shared_preferences: ^2.3.0
  url_launcher: ^6.3.1
  share_plus: ^13.3.1
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  table_calendar: ^3.1.2
  file_picker: ^13.1.0
  csv: ^6.0.0
  qr_flutter: ^4.1.0
  http: ^1.2.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  generate: true

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#0F172A"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
